# nixpacks.toml - Исправленная версия

[phases.setup]
# Добавлены три точки "..." в начале списка
nixPkgs = ["...", "python3", "gcc", "zlib", "libjpeg", "libpng", "freetype"]

[start]
command = "python3 doc_bot.py"
