# nixpacks.toml - Версия "План Б"

[phases.setup]
# Указываем конкретную версию Python и пакеты
nixPkgs = ["...", "python311", "zlib", "jpeg", "libpng", "freetype"]

[phases.install]
# Явно указываем команду установки
cmds = ["pip install -r requirements.txt"]

[start]
# Явно указываем команду запуска
command = "python3 doc_bot.py"
